apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: micro-user
  name: micro-user
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: micro-user
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: DATABASE_HOST
              value: 112.126.99.74:33006
            - name: DATABASE_NAME
              value: kaoyayacn
            - name: DATABASE_PASSWORD
              value: kaoyayacom2017
            - name: DATABASE_USER
              value: root
            - name: MASTER_DB_HOST
              value: 112.126.99.74:33006
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: kaoyayacom2017
            - name: MASTER_DB_USER
              value: root
            - name: REDIS_AUTH
              value: ""
            - name: REDIS_HOST
              value: 192.168.118.174:6379
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/user:dev
          imagePullPolicy: Always
          name: micro-user
          resources: {}
      restartPolicy: Always
