# 统计班级学习详情
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: student-learning-record
  name: student-learning-record
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: "30 2 * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: student-learning-record
    spec:
      template:
        spec:
          containers:
            - env:
                - name: MASTER_DB_HOST
                  value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
                - name: MASTER_DB_NAME
                  value: sq_kaoyaya
                - name: MASTER_DB_PASSWORD
                  value: tdHRdT7V2o4d
                - name: MASTER_DB_USER
                  value: kyy_master
                - name: QUESTION_DB_HOST
              value: rm-2ze1284oau0bzbz97.mysql.rds.aliyuncs.com
                       - name: QUESTION_DB_NAME
                       value: question
                       - name: QUESTION_DB_PASSWORD
                         value: Nd1Gt6IgddAu
                       - name: QUESTION_DB_USER
                         value: kyy_question
                       - name: REDIS_AUTH
                         value: 9V3zrtA338ULq6N7s2
                       - name: REDIS_HOST
                         value: r-2ze6269f42e1f8c4.redis.rds.aliyuncs.com:6379
              image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/student-learning-record:v1.0
              name: student-learning-record
              resources: {}
          restartPolicy: Never
