# 错题分析
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: question-analysis
  name: question-analysis
spec:
  concurrencyPolicy: Forbid
  schedule: "1 0 * * 1"
  successfulJobsHistoryLimit: 1
  suspend: false
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: question-analysis
    spec:
      template:
        metadata:
          labels:
            app: question-analysis
        spec:
          containers:
            - env:
                - name: QUESTION_DB_HOST
                  value: rm-2ze1284oau0bzbz97.mysql.rds.aliyuncs.com
                - name: QUESTION_DB_NAME
                  value: question
                - name: QUESTION_DB_PASSWORD
                  value: Nd1Gt6IgddAu
                - name: QUESTION_DB_USER
                  value: kyy_question
              image: registry.cn-qingdao.aliyuncs.com/kaoyaya/question-analysis:latest
              name: question-analysis
              resources: {}
          restartPolicy: Always
