apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      spec:
      containers:
        - image: redis:2.8
          name: redis
          ports:
            - containerPort: 6379
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
