apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ack-consul
    chart: ack-consul-0.5.0
    heritage: Tiller
    release: ack-consul
  name: ack-consul-server
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ack-consul
      chart: ack-consul-0.5.0
      component: server
      hasDNS: 'true'
      release: ack-consul
  serviceName: ack-consul-server
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'false'
      labels:
        app: ack-consul
        chart: ack-consul-0.5.0
        component: server
        hasDNS: 'true'
        release: ack-consul
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: ack-consul
                  component: server
                  release: ack-consul
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - /bin/sh
            - '-ec'
            - |
              CONSUL_FULLNAME="ack-consul"

              exec /bin/consul agent \
                -advertise="${POD_IP}" \
                -bind=0.0.0.0 \
                -bootstrap-expect=3 \
                -client=0.0.0.0 \
                -config-dir=/consul/config \
                -datacenter=dc1 \
                -data-dir=/consul/data \
                -domain=consul \
                -hcl="connect { enabled = true }" \
                -ui \
                -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
                -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
                -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
                -server
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: 'consul:1.3.1'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - consul leave
          name: consul
          ports:
            - containerPort: 8500
              name: http
              protocol: TCP
            - containerPort: 8301
              name: serflan
              protocol: TCP
            - containerPort: 8302
              name: serfwan
              protocol: TCP
            - containerPort: 8300
              name: server
              protocol: TCP
            - containerPort: 8600
              name: dns-tcp
              protocol: TCP
            - containerPort: 8600
              name: dns-udp
              protocol: UDP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-ec'
                - |
                  curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
                  grep -E '".+"'
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /consul/data
              name: data
            - mountPath: /consul/config
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            defaultMode: 420
            name: ack-consul-server-config
          name: config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: alicloud-disk-efficiency
