apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '1'
  labels:
    app: ack-consul
    chart: ack-consul-0.5.0
    heritage: Tiller
    release: ack-consul
  name: ack-consul
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ack-consul
      chart: ack-consul-0.5.0
      component: client
      hasDNS: 'true'
      release: ack-consul
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'false'
      labels:
        app: ack-consul
        chart: ack-consul-0.5.0
        component: client
        hasDNS: 'true'
        release: ack-consul
    spec:
      containers:
        - command:
            - /bin/sh
            - '-ec'
            - |
              CONSUL_FULLNAME="ack-consul"

              exec /bin/consul agent \
                -node="${NODE}" \
                -advertise="${POD_IP}" \
                -bind=0.0.0.0 \
                -client=0.0.0.0 \
                -config-dir=/consul/config \
                -datacenter=dc1 \
                -data-dir=/consul/data \
                -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
                -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
                -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
                -domain=consul
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: 'consul:1.3.1'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - consul leave
          name: consul
          ports:
            - containerPort: 8500
              hostPort: 8500
              name: http
              protocol: TCP
            - containerPort: 8502
              hostPort: 8502
              name: grpc
              protocol: TCP
            - containerPort: 8301
              name: serflan
              protocol: TCP
            - containerPort: 8302
              name: serfwan
              protocol: TCP
            - containerPort: 8300
              name: server
              protocol: TCP
            - containerPort: 8600
              name: dns-tcp
              protocol: TCP
            - containerPort: 8600
              name: dns-udp
              protocol: UDP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-ec'
                - |
                  curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
                  grep -E '".+"'
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /consul/data
              name: data
            - mountPath: /consul/config
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: data
        - configMap:
            defaultMode: 420
            name: ack-consul-client-config
          name: config
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 4
  observedGeneration: 1
  updatedNumberScheduled: 4
