# Source: ack-consul/templates/dns-service.yaml
# Service for Consul DNS.
apiVersion: v1
kind: Service
metadata:
  name: ack-consul-dns
  namespace: default
  labels:
    app: ack-consul
    chart: ack-consul-0.5.0
    heritage: Tiller
    release: consul
spec:
  ports:
    - name: dns-tcp
      port: 53
      protocol: "TCP"
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: "UDP"
      targetPort: dns-udp
  selector:
    app: ack-consul
    release: "consul"
    hasDNS: "true"
