apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-jenkins
spec:
  # 设置容量
  capacity:
    storage: 20Gi
  # 访问模式
  accessModes:
    # 该卷能够以读写模式被多个节点同时加载
    - ReadWriteOnce
  # 回收策略，这里是基础擦除 `rm-rf/thevolume/*`
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    # NFS 服务端配置的路径
    path: "/data/k8s/"
    # NFS 服务端地址
    server: 127.0.0.1
    readOnly: false
