apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-redis
  name: k8s-redis
spec:
  replicas: 1
  selector:
   matchLabels:
     app: k8s-redis
  template:
    metadata:
      labels:
        app: k8s-redis
    spec:
      containers:
        - name: k8s-redis
          image: redis:latest
          volumeMounts:
          - name: redis-data
            mountPath: "/data"
          ports:
            - containerPort: 6379
              hostPort: 6379
          resources: {}
      restartPolicy: Always
      volumes:
      - name: redis-data
        hostPath:
          path: /Users/mikoto/data/redis
          type: Directory
