apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: micro-comment
  name: micro-comment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: micro-comment
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: MASTER_DB_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: tdHRdT7V2o4d
            - name: MASTER_DB_USER
              value: kyy_master
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/comment:latest
          name: micro-comment
          resources: {}
      restartPolicy: Always
