apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: >-
      {"holderIdentity":"212f1240-a15e-11e9-bc24-4e88964fc968","leaseDurationSeconds":15,"acquireTime":"2019-07-20T15:14:34Z","renewTime":"2019-07-20T15:14:38Z","leaderTransitions":0}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: alicloud/disk
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: jenkins
    chart: jenkins-0.9.0
    heritage: Tiller
    release: jenkins
  name: jenkins-home-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicould-disk-local-storage
  volumeName: jenkins-local-pv
