apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch-claim0
  name: elasticsearch-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
