apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: nuxt-kc
  name: nuxt-kc
spec:
  rules:
    - host: "www.kuaixuezaixian.com"
      http:
        paths:
          - backend:
              serviceName: nuxt-kc
              servicePort: 3000
            path: /kc/

