#双十一
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: double-eleven
  labels:
    app: double-eleven
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: double-eleven
    spec:
      template:
        spec:
          containers:
            - env:
                - name: MASTER_DB_HOST
                  value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
                - name: MASTER_DB_NAME
                  value: sq_kaoyaya
                - name: MASTER_DB_PASSWORD
                  value: tdHRdT7V2o4d
                - name: MASTER_DB_USER
                  value: kyy_master
              image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/double-eleven:v1.0
              name: double-eleven
              resources: {}
          restartPolicy: Never
