apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sync-bdp-mysqldump
  name: sync-bdp-mysqldump
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: sync-bdp-mysqldump
    spec:
      containers:
        - env:
            - name: TABLES
              value: "orders_bill"
          image: registry-vpc.cn-beijing.aliyuncs.com/kaoyaya/mysqldump:bdp
          imagePullPolicy: Always
          name: sync-bdp-mysqldump
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
