apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mq-order-open-services
  name: mq-order-open-services
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mq-order-open-services
    spec:
      containers:
        - env:
            - name: MASTER_DB_HOST
              value: 112.126.99.74:33006
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: kaoyayacom2017
            - name: MASTER_DB_USER
              value: root
            - name: REDIS_AUTH
              value: ""
            - name: REDIS_HOST
              value: 192.168.118.174:6379
            - name: KAOYAYA # 考呀呀内网服务名
              value: php-kaoyayacom
            - name: RUN_MODE
              value: dev
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/open-services:latest
          name: mq-order-open-services
          resources: {}
      restartPolicy: Always
