apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: sync-video-duration
  name: sync-video-duration
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sync-video-duration
    spec:
      containers:
        - env:
            - name: MASTER_DB_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: tdHRdT7V2o4d
            - name: MASTER_DB_USER
              value: kyy_master
          image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/sync-video-duration:latest
          imagePullPolicy: Always
          name: sync-video-duration
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}