# 定时开放考场
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nuxt-kc-crontab
  labels:
    app: nuxt-kc-crontab
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */1 * * * "
  successfulJobsHistoryLimit: 1
  suspend: false
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: nuxt-kc-crontab
    spec:
      template:
        spec:
          containers:
            - env:
              - name: MASTER_DB_HOST
                value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
              - name: MASTER_DB_NAME
                value: sq_kaoyaya
              - name: MASTER_DB_PASSWORD
                value: tdHRdT7V2o4d
              - name: MASTER_DB_USER
                value: kyy_master
              - name: PORT
                value: "80"
              - name: RUN_MODE
                value: production
              image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/nuxt-kc-crontab:v1.0
              name: nuxt-kc-crontab
              resources: {}
          restartPolicy: Never
