apiVersion: v1
kind: Service
metadata:
  labels:
    app: wx-article-server
  name: wx-article-server
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: wx-article-server
