apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mq-question-record
  name: mq-question-record
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mq-question-record
    spec:
      imagePullSecrets:
        - name: beijing
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            # 使用题库
            - name: QUESTION_DB_HOST
              value: 192.168.3.220:33006
            - name: QUESTION_DB_NAME
              value: question
            - name: QUESTION_DB_PASSWORD
              value: kaoyayacom2017
            - name: QUESTION_DB_USER
              value: root
            - name: REDIS_AUTH
              value: ""
            - name: REDIS_HOST
              value: redis:6379
            - name: RUN_MODE
              value: dev
          image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/question-record:dev
          name: mq-question-record
      restartPolicy: Always
