apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: fe-tiku-pc
  name: fe-tiku-pc
  annotations:
    nginx.ingress.kubernetes.io/server-alias: "lzh.kyy.com,caishidian.kyy.com"
spec:
  rules:
    - host: 'www.kyy.com'
      http:
        paths:
          - backend:
              serviceName: fe-tiku-pc
              servicePort: 80
            path: /tiku/pc/

