apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mq-question-record
  name: mq-question-record
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mq-question-record
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            # 使用题库
            - name: DATABASE_HOST
              value: rm-2ze1284oau0bzbz97.mysql.rds.aliyuncs.com
            - name: DATABASE_NAME
              value: question
            - name: DATABASE_PASSWORD
              value: Nd1Gt6IgddAu
            - name: DATABASE_USER
              value: kyy_question
            - name: REDIS_AUTH
              value: 9V3zrtA338ULq6N7s2
            - name: REDIS_HOST
              value: r-2ze6269f42e1f8c4.redis.rds.aliyuncs.com:6379
            - name: RUN_MODE
              value: production
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/question-record:latest
          name: mq-question-record
      restartPolicy: Always
