# 代理提成计算
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mq-push-task
  labels:
    app: mq-push-task
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mq-push-task
    spec:
      containers:
        - env:
            - name: MASTER_DB_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: tdHRdT7V2o4d
            - name: MASTER_DB_USER
              value: kyy_master
            - name: WECHAT_DB_HOST
              value: rm-2zeb1f93086857hv0.mysql.rds.aliyuncs.com
            - name: WECHAT_DB_NAME
              value: wechat
            - name: WECHAT_DB_PASSWORD
              value: 4PYmsab4Ukyh
            - name: WECHAT_DB_USER
              value: kyy_yuncms
            - name: MAXCOMPUTE_DB_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: MAXCOMPUTE_DB_NAME
              value: maxcompute
            - name: MAXCOMPUTE_DB_PASSWORD
              value: tdHRdT7V2o4d
            - name: MAXCOMPUTE_DB_USER
              value: kyy_master
            - name: DATABASE_HOST
              value: rm-2zeb1f93086857hv0.mysql.rds.aliyuncs.com
            - name: DATABASE_NAME
              value: kaoyaya_yuncms
            - name: DATABASE_PASSWORD
              value: 4PYmsab4Ukyh
            - name: DATABASE_USER
              value: kyy_yuncms
            - name: REDIS_AUTH
              value: 9V3zrtA338ULq6N7s2
            - name: REDIS_HOST
              value: r-2ze6269f42e1f8c4.redis.rds.aliyuncs.com:6379
          image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/push-task-mq:v1.3
          name: mq-push-task
          resources: {}
      restartPolicy: Always
