# 微信上课提醒
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: double-eleven
  labels:
    app: double-eleven
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: double-eleven
    spec:
      template:
        spec:
          containers:
            - env:
                  - name: MASTER_DB_HOST
                    value: 192.168.3.220:33006
                  - name: MASTER_DB_NAME
                    value: sq_kaoyaya
                  - name: MASTER_DB_PASSWORD
                    value: kaoyayacom2017
                  - name: MASTER_DB_USER
                    value: root
              image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/double-eleven:dev
              name: double-eleven
              resources: {}
          restartPolicy: Never
