apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: micro-short-url
  name: micro-short-url
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: micro-short-url
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: DATABASE_HOST
              value: 112.126.99.74:33006
            - name: DATABASE_NAME
              value: kaoyayacn
            - name: DATABASE_PASSWORD
              value: kaoyayacom2017
            - name: DATABASE_USER
              value: root
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/short-url
          name: micro-short-url
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
