# 直播回看数据同步
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: live-reply-visitor
  labels:
    app: live-reply-visitor
spec:
  concurrencyPolicy: Forbid
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: live-reply-visitor
    spec:
      template:
        metadata:
          labels:
            app: live-reply-visitor
        spec:
          containers:
            - env:
                - name: MASTER_DB_HOST
                  value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
                - name: MASTER_DB_NAME
                  value: sq_kaoyaya
                - name: MASTER_DB_PASSWORD
                  value: tdHRdT7V2o4d
                - name: MASTER_DB_USER
                  value: kyy_master
                - name: REDIS_AUTH
                  value: 9V3zrtA338ULq6N7s2
                - name: REDIS_HOST
                  value: r-2ze6269f42e1f8c4.redis.rds.aliyuncs.com:6379
                - name: RUN_MODE
                  value: production
              image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/live-reply-visitor:v1.0
              name: live-reply-visitor
              resources: {}
          restartPolicy: Never

