# 小程序服务端

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: taxation-server
  name: taxation-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: taxation-server
    spec:
      containers:
        - env:
            - name: ADDRESS
              value: 0.0.0.0:3002
            - name: DATABASE_HOST
              value: 112.126.99.74
            - name: DATABASE_NAME
              value: taxation
            - name: DATABASE_PASSWORD
              value: kaoyayacom2017
            - name: DATABASE_USER
              value: root
          image:  registry.cn-beijing.aliyuncs.com/kaoyaya/taxation-server:latest
          name: taxation-server
          ports:
            - containerPort: 3002
          resources: {}
      restartPolicy: Always
