apiVersion: v1
kind: Service
metadata:
  labels:
    app: taxation-server
  name: taxation-server
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    app: taxation-server
