apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: micro-edu
  name: micro-edu
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: micro-edu
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: DATABASE_HOST
              value: rm-2zeb1f93086857hv0.mysql.rds.aliyuncs.com
            - name: DATABASE_NAME
              value: kaoyaya_yuncms
            - name: DATABASE_PASSWORD
              value: 4PYmsab4Ukyh
            - name: DATABASE_USER
              value: kyy_yuncms
            - name: MASTER_DB_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: tdHRdT7V2o4d
            - name: MASTER_DB_USER
              value: kyy_master
            - name: RUN_MODE
              value: production
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/edu:latest
          name: micro-edu
          resources: {}
      restartPolicy: Always
