apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: short-url
  name: short-url
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: short-url
    spec:
      imagePullSecrets:
        - name: qingdao
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          name: short-url
          env:
            - name: MASTER_DB_HOST
              value: 112.126.99.74:33006
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: kaoyayacom2017
            - name: MASTER_DB_USER
              value: root
            - name: REDIS_AUTH
              value: ""
            - name: REDIS_HOST
              value: 192.168.118.174:6379
            - name: RUN_MODE
              value: dev
            - name: SHORTURL_DB_HOST
              value: 112.126.99.74:33006
            - name: SHORTURL_DB_NAME
              value: short-url
            - name: SHORTURL_DB_USER
              value: root
            - name: SHORTURL_DB_PASSWORD
              value: kaoyayacom2017
            - name: PORT
              value: "80"
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya/short-url-web-gin:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
