apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: sync-question-video-comment
  name: sync-question-video-comment
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sync-question-video-comment
    spec:
      containers:
        - env:
            - name: MASTER_DB_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: tdHRdT7V2o4d
            - name: MASTER_DB_USER
              value: kyy_master
            - name: QUESTION_DB_HOST
              value: rm-2ze1284oau0bzbz97.mysql.rds.aliyuncs.com
            - name: QUESTION_DB_NAME
              value: question
            - name: QUESTION_DB_PASSWORD
              value: Nd1Gt6IgddAu
            - name: QUESTION_DB_USER
              value: kyy_question
          image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/sync-question-video-comment:latest
          imagePullPolicy: Always
          name: sync-question-video-comment
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}