apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wechat-web
  name: wechat-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: wechat-web
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: DATABASE_HOST
              value: 192.168.3.220:33006
            - name: DATABASE_NAME
              value: kaoyayacn
            - name: DATABASE_PASSWORD
              value: kaoyayacom2017
            - name: DATABASE_USER
              value: root
            - name: MASTER_DB_HOST
              value: 192.168.3.220:33006
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: kaoyayacom2017
            - name: MASTER_DB_USER
              value: root
            - name: PORT
              value: "80"
            - name: REDIS_AUTH
              value: ""
            - name: REDIS_HOST
              value: redis:6379
            - name: REPLY_CACHE
              value: "false"
            - name: SOCKET_SERVICE
              value: wechat-im-socket:8000
            - name: WECHAT_DB_HOST
              value: 192.168.3.220:33006
            - name: WECHAT_DB_NAME
              value: wechat
            - name: WECHAT_DB_PASSWORD
              value: kaoyayacom2017
            - name: WECHAT_DB_USER
              value: root
            - name: RUN_MODE
              value: dev
          image: registry.cn-qingdao.aliyuncs.com/wechat-open/web:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          name: wechat-web
          resources: {}
      restartPolicy: Always
