apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sync-wxmsg-pagigation
  name: sync-wxmsg-pagigation
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: sync-wxmsg-pagigation
    spec:
      containers:
        - env:
            - name: WECHAT_DB_HOST
              value: rm-2zeb1f93086857hv0.mysql.rds.aliyuncs.com
            - name: WECHAT_DB_NAME
              value: wechat
            - name: WECHAT_DB_PASSWORD
              value: 4PYmsab4Ukyh
            - name: WECHAT_DB_USER
              value: kyy_yuncms
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/sync-wxmsg-pagigation
          imagePullPolicy: Always
          name: sync-wxmsg-pagigation
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30

