apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dev-mysql
  name: dev-mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: dev-mysql
    spec:
      imagePullSecrets:
        - name: beijing
      spec:
      volumes:
        - name: dev-mysql
          hostPath:
            path: /data/db/
      containers:
        - image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          name: dev-mysql
          ports:
            - containerPort: 3306
              hostPort: 33006
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dev-mysql
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
