apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: micro-question-new
  name: micro-question-new
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: micro-question-new
    spec:
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: DATABASE_HOST
              value: rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
            - name: DATABASE_NAME
              value: sq_kaoyaya
            - name: DATABASE_PASSWORD
              value: tdHRdT7V2o4d
            - name: DATABASE_USER
              value: kyy_master
            - name: QUESTION_CASH
              value: "false"
            - name: QUESTION_DB_HOST
              value: rm-2ze1284oau0bzbz97.mysql.rds.aliyuncs.com
            - name: QUESTION_DB_NAME
              value: question
            - name: QUESTION_DB_PASSWORD
              value: Nd1Gt6IgddAu
            - name: QUESTION_DB_USER
              value: kyy_question
            - name: REDIS_AUTH
              value: 9V3zrtA338ULq6N7s2
            - name: REDIS_HOST
              value: r-2ze6269f42e1f8c4.redis.rds.aliyuncs.com:6379
            - name: RUN_MODE
              value: production
          image: registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/question-new:latest
          name: micro-question-new
          resources: {}
      restartPolicy: Always
