apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-api
  name: go-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: go-api
    spec:
      imagePullSecrets:
        - name: beijing
      containers:
        - args:
            - --registry_address=consul-server-bootstrap:8500
          env:
            - name: DATABASE_HOST
              value: 112.126.99.74:33006
            - name: DATABASE_NAME
              value: kaoyayacn
            - name: DATABASE_PASSWORD
              value: kaoyayacom2017
            - name: DATABASE_USER
              value: root
            - name: ELASTICESEARCH_HOST
              value: http://elasticsearch:9200
            - name: MASTER_DB_HOST
              value: 112.126.99.74:33006
            - name: MASTER_DB_NAME
              value: sq_kaoyaya
            - name: MASTER_DB_PASSWORD
              value: kaoyayacom2017
            - name: MASTER_DB_USER
              value: root
            - name: QUESTION_DB_HOST
              value: 112.126.99.74:33006
            - name: QUESTION_DB_NAME
              value: question
            - name: QUESTION_DB_PASSWORD
              value: kaoyayacom2017
            - name: QUESTION_DB_USER
              value: root
            - name: REDIS_AUTH
              value: ""
            - name: REDIS_HOST
              value: 192.168.118.174:6379
            - name: WECHAT_DB_HOST
              value: 112.126.99.74:33006
            - name: WECHAT_DB_NAME
              value: wechat
            - name: WECHAT_DB_PASSWORD
              value: kaoyayacom2017
            - name: WECHAT_DB_USER
              value: wechat
            - name: PORT
              value: "80"
            - name: RUN_MODE
              value: dev
          image: registry.cn-beijing.aliyuncs.com/kaoyaya-micro/api-web:dev
          name: go-api
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
