version: "2"
labels:
  aliyun.schedule: "0 0 4 * * *"
services:
  order-bill:
    image: "registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/order-bill:0701"
    environment:
      - RUN_MODE=production
      - PORT=80
      - MASTER_DB_HOST=rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
      - MASTER_DB_NAME=sq_kaoyaya
      - MASTER_DB_USER=kyy_master
      - MASTER_DB_PASSWORD=tdHRdT7V2o4d
      - DATABASE_HOST=test.server.kaoyaya.com:3306
      - DATABASE_NAME=bdp
      - DATABASE_USER=root
      - DATABASE_PASSWORD=kaoyayacom2017
