apiVersion: v1
kind: Service
metadata:
  annotations:
    aliyun.log_store_s1: /var/log/apache2/error*.log
    aliyun.proxy.VIRTUAL_HOST: https://www.kaoyaya.com,http://www.kaoyaya.com,http://kaoyaya.com,http://caishidian.kaoyaya.com,http://www.caishidian.com,http://www.91sanmiao.com,http://www.119test.com
    aliyun.proxy.VIRTUAL_HOST_WEIGHT: "22"
    kompose.cmd: kompose-darwin-amd64 convert -f php-sanmiao.yaml
    kompose.version: 1.17.0 (70e82c92)

  labels:
    app: php-sanmiao
  name: php-sanmiao
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: php-sanmiao
status:
  loadBalancer: {}
