version: "2"
labels:
  aliyun.schedule: "0 0-59/10 9-21 * * *"
services:
    class-remind:
       image: "registry.cn-qingdao.aliyuncs.com/kaoyaya-micro/class-remind:v1.9"
       environment:
        - RUN_MODE=production
        - PORT=80
        - MASTER_DB_HOST=rm-2ze8m2daqb051wp49.mysql.rds.aliyuncs.com
        - MASTER_DB_NAME=sq_kaoyaya
        - MASTER_DB_USER=kyy_master
        - MASTER_DB_PASSWORD=tdHRdT7V2o4d
        - WECHAT_DB_HOST=rm-2zeb1f93086857hv0.mysql.rds.aliyuncs.com
        - WECHAT_DB_NAME=wechat
        - WECHAT_DB_USER=kyy_yuncms
        - WECHAT_DB_PASSWORD=4PYmsab4Ukyh
        - REDIS_HOST=r-2ze6269f42e1f8c4.redis.rds.aliyuncs.com:6379
        - REDIS_AUTH=9V3zrtA338ULq6N7s2
